// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mini-dreams/FamilleNature.tsx": () => import("../components/mockups/mini-dreams/FamilleNature.tsx"),
  "./components/mockups/mini-dreams/LuxeJunior.tsx": () => import("../components/mockups/mini-dreams/LuxeJunior.tsx"),
  "./components/mockups/mini-dreams/ParcDeReves.tsx": () => import("../components/mockups/mini-dreams/ParcDeReves.tsx")
};
